export const YOUTUBE_SEARCH_LOADING = 'YOUTUBE_SEARCH_LOADING';
export const YOUTUBE_SEARCH_SUCCESS = 'YOUTUBE_SEARCH_SUCCESS';
export const YOUTUBE_SEARCH_ERROR = 'YOUTUBE_SEARCH_ERROR';

export const YOUTUBE_FETCH_MORE_SUCCESS = 'YOUTUBE_FETCH_MORE_SUCCESS';

export const MODAL_OPEN = 'MODAL_OPEN';
export const MODAL_CLOSE = 'MODAL_CLOSE';

export const VIDEO_SAVE = 'VIDEO_SAVE';
export const VIDEO_DELETE = 'VIDEO_DELETE';

export const PAGE_CHANGE = 'PAGE_CHANGE';

export const WATCHED_TOGGLE = 'WATCHED_TOGGLE';
