export const YOUTUBE_SEARCH_LOADING = 'YOUTUBE_SEARCH_LOADING';
export const YOUTUBE_SEARCH_SUCCESS = 'YOUTUBE_SEARCH_SUCCESS';
export const YOUTUBE_SEARCH_ERROR = 'YOUTUBE_SEARCH_ERROR';

export const MODAL_OPEN = 'MODAL_OPEN';
export const MODAL_CLOSE = 'MODAL_CLOSE';
