export const LOCAL_SEARCH_LIST = 'LOCAL_SEARCHLIST';
export const LOCAL_SAVE_VIDEO_LIST = 'LOCAL_SAVE_VIDEO_LIST';
export const LOCAL_RECENT_SEARCH_KEYWORDS = 'LOCAL_RECENTSEARCH_KEYWORDS';
export const LOCAL_CURRENT_SEARCH_INFO = 'LOCAL_CURRENT_SEARCH_INFO';
export const LOCAL_CURRENT_PAGE = 'LOCAL_CURRENT_PAGE';
